apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-sql-pv-claim
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard-rwo 
  resources:
    requests:
      storage: 4Gi
      
