apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: myreplicaset
  labels: 
    app: myapp
    env: dev
spec:
  replicas: 3
  selector:
    matchLabels:
      key: replica-value
  template:
    metadata:
      labels:
        key: template-value
    spec:
      containers:
        - name: myapp
          image: nginx:latest
---




