apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-object
  labels:
  
    env: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      env: dev 
  template:
    metadata:
      labels:
        env: dev
         #this should key value should match to the pod lablel so that service will stablish the conncetion between

    spec:
      containers:
        - name: nginx-image
          image: nginx:latest
          ports:
          - containerPort: 80
          # resources:
          #   requests:
          #     memory: "128Mi"
          #     cpu: "500m"
          #   limits:
          #     memory: "128Mi"
          #     cpu: "500m"