apiVersion: apps/v1
kind: Deployment
metadata:
  name: proshop-backend-deployment
  labels:
    app: proshop-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: proshop-backend
  template:
    metadata:
      labels:
        app: proshop-backend
    spec:
      containers:
      - name: proshop-backend
        # Public Docker image for your backend
        image: arun2565/my-app-backend:tag22
        ports:
        - containerPort: 5000
        env:
        - name: NODE_ENV
          value: "production"
        - name: MONGO_URI
          value: "mongodb+srv://arunponugoti2565:yFb6W7mPgFdogvsV@project2565.svvyp.mongodb.net/myDatabase?retryWrites=true&w=majority&appName=project2565"
        - name: JWT_SECRET
          value: "abc123"
---
apiVersion: v1
kind: Service
metadata:
  name: proshop-backend-service
  labels:
    app: proshop-backend
spec:
  type: ClusterIP
  selector:
    app: proshop-backend
  ports:
    - port: 5000
      targetPort: 5000
