apiVersion: networking.gke.io/v1
kind: ManagedCertificate
metadata:
  name: gkecloud-com-cert  # Same as referenced in the Ingress
spec:
  domains:
    - gkecloud.com  # Your domain name

# kubectl describe managedcertificate gkecloud-com-cert
# this command will give you full info about this script , if status is provisioning it is still , 
# you have to wait for few mins, if the status is looks like active then it is working
