replicaCount: 2

image:
  repository: arun2565/backend-internship-app
  tag: tag15
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 9005

ingress:
  enabled: false
  annotations: {}
  hosts:
    - host: backend.myapp.com
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

env:
  DATABASE_URL: postgresql+asyncpg://postgres:password@junction.proxy.rlwy.net:45520/railway"


resources: {}
nodeSelector: {}
tolerations: []
affinity: {}
