replicaCount: 1
fullnameOverride: ""
nameOverride: ""

image:
  repository: arun2565/backend-internship-app
  tag: 1.0.7
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 9005

database:
  url: "postgresql+asyncpg://postgres:password@junction.proxy.rlwy.net:45520/railway"  # Fixed and referenced properly

resources: {}
nodeSelector: {}
tolerations: []
affinity: {}

serviceAccount:
  create: false
  name: ""
