{{- if and .Values.serviceAccount .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.name | default .Release.Name }}
  namespace: {{ .Release.Namespace }}
  annotations:
    some-annotation: "value"
{{- end }}
