apiVersion: v1
kind: Service
metadata:
  name: {{ include "myapp.fullname" . }}-internal-service
spec:
  type: ClusterIP
  selector:
    app: {{ include "myapp.name" . }}
  ports:
    - port: {{ .Values.internalService.port }}
      targetPort: 80
