name: 02-manifest-file-deployment

on: 
  workflow_dispatch: 
    inputs:
      action:
        description: "Action to perform on the Kubernetes manifest (apply or delete)"
        default: none
        type: choice
        options:
          - apply
          - delete
        required: true
      gke_cluster_name:
        description: 'select the gke cluster name'
        default: 'sap-dev-gke-cluster'
        required: true
        type: choice
        options:
          - 'tmproject-dev-private-cluster'
          - 'sap-dev-gke-cluster'
<<<<<<< HEAD
          - ' gke-public-cluster'
=======
          - 'gke-public-cluster'
>>>>>>> origin/main
      gcp_project:
        description: 'select the project'
        default: 'turnkey-guild-441104-f3'
        required: true
        type: choice
        options:
          - 'turnkey-guild-441104-f3'

      gcp_region_zone:
        description: 'select the region or zone'
        default: 'zone'
        required: true
        type: choice
        options:
          - 'zone'
          - 'region'
      gcp_location:
        description: 'select the location'
        default: 'us-east1-b'
        required: true
        type: choice
        options:
          - 'us-east1-b'
          - 'asia-southeast1'
          - 'us-central1'
      manifest_file:
        description: 'select the manifest deployment file'
        default: '02-GKE_Storage_project'
        required: true
        type: choice
        options:
          - '01-nginx-deployment.yaml'
          - '02-replicasets.yaml'
          - '03-Deployment_manifest.yaml'
          - '04-Service_manifest.yaml'
          - '05-ReplicaSet.yaml'
          - '02-GKE_Storage_project'

          


jobs:
  k8s-deployment-2:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4
      
      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ inputs.action.gcp_project }}
          install_components: 'beta'
      
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Install gke-gcloud-auth-plugin
        run: |
            gcloud components install gke-gcloud-auth-plugin
      
      - name: Authenticate with GKE
        run: |
          gcloud container clusters get-credentials ${{inputs.gke_cluster_name}} \
          --${{inputs.gcp_region_zone}} ${{inputs.gcp_location}}


      - name: Apply K8s manifest file
        if: ${{ inputs.action == 'apply' }}
        run: |
            kubectl apply -f ${{inputs.manifest_file}}
      - name: Delete the k8s manifest file
        if: ${{ inputs.action == 'delete' }}
        run: |
            kubectl delete -f ${{inputs.manifest_file}}
      
      
          
