name: 04-Update Password Inside Container

on: 
  workflow_dispatch: 
    inputs:
      root_password:
        description: "Provide the root password"
        required: true
        type: string
      pod_name:
        description: "Enter the pod name where the container is running"
        required: true
        type: string
      container_name:
        description: "Enter the container name (optional)"
        required: false
        type: string
      gke_cluster_name:
        description: 'Select the GKE cluster name'
        default: 'sap-dev-gke-cluster'
        required: true
        type: choice
        options:
          - 'tmproject-dev-private-cluster'
          - 'sap-dev-gke-cluster'
      gcp_project:
        description: 'Select the project'
        default: 'turnkey-guild-441104-f3'
        required: true
        type: choice
        options:
          - 'turnkey-guild-441104-f3'
      gcp_region_zone:
        description: 'Select the region or zone'
        default: 'zone'
        required: true
        type: choice
        options:
          - 'zone'
          - 'region'
      gcp_location:
        description: 'Select the location'
        default: 'us-east1-b'
        required: true
        type: choice
        options:
          - 'us-east1-b'
          - 'asia-southeast1'

jobs:
  update-password:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}
      
      - name: Install gke-gcloud-auth-plugin
        run: |
          # Add Google Cloud CLI repository
          echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] https://packages.cloud.google.com/apt cloud-sdk main" | sudo tee -a /etc/apt/sources.list.d/google-cloud-sdk.list
          sudo apt-get install -y apt-transport-https ca-certificates
          curl -fsSL https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo tee /usr/share/keyrings/cloud.google.gpg > /dev/null

          # Update and install the plugin
          sudo apt-get update
          sudo apt-get install -y google-cloud-cli-gke-gcloud-auth-plugin


      - name: Authenticate with GKE
        run: |
          gcloud container clusters get-credentials ${{ inputs.gke_cluster_name }} \
          --${{ inputs.gcp_region_zone }} ${{ inputs.gcp_location }}

      - name: Encrypt the root password
        run: |
          # Define the command to run in the container
          ENCRYPT_COMMAND="echo '${{ inputs.root_password }}' | base64"

          # Check if container name is provided
          if [[ -n "${{ inputs.container_name }}" ]]; then
            kubectl exec -it ${{ inputs.pod_name }} -c ${{ inputs.container_name }} -- /bin/bash -c "$ENCRYPT_COMMAND"
          else
            kubectl exec -it ${{ inputs.pod_name }} -- /bin/bash -c "$ENCRYPT_COMMAND"
          fi
        shell: bash
