name: 04-Update Password Inside Container

on: 
  workflow_dispatch: 
    inputs:
      root_password:
        description: "Provide the root password"
        required: true
        type: string
      pod_name:
        description: "Enter the pod name where the container is running"
        required: true
        type: string
      container_name:
        description: "Enter the container name (optional)"
        required: false
        type: string
      gke_cluster_name:
        description: 'Select the GKE cluster name'
        default: 'sap-dev-gke-cluster'
        required: true
        type: choice
        options:
          - 'tmproject-dev-private-cluster'
          - 'sap-dev-gke-cluster'
      gcp_project:
        description: 'Select the project'
        default: 'turnkey-guild-441104-f3'
        required: true
        type: choice
        options:
          - 'turnkey-guild-441104-f3'
      gcp_region_zone:
        description: 'Select the region or zone'
        default: 'zone'
        required: true
        type: choice
        options:
          - 'zone'
          - 'region'
      gcp_location:
        description: 'Select the location'
        default: 'us-east1-b'
        required: true
        type: choice
        options:
          - 'us-east1-b'
          - 'asia-southeast1'

jobs:
  k8s-deployment-2:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4
      
      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ inputs.action.gcp_project }}
          install_components: 'beta'
      
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Install gke-gcloud-auth-plugin
        run: |
            gcloud components install gke-gcloud-auth-plugin
      
      - name: Authenticate with GKE
        run: |
          gcloud container clusters get-credentials ${{inputs.gke_cluster_name}} \
          --${{inputs.gcp_region_zone}} ${{inputs.gcp_location}}

      - name: Encrypt root password inside container
        run: |
          # Check if password_manager exists
          which password_manager || echo "password_manager not found"
          
          # Check if keystore file exists
          kubectl exec -i ${{ inputs.pod_name }} -c ${{ inputs.container_name }} -- ls -l /opt/actimize/ais_server/Instances/actimize_server_1/ais.keystore
          
          # Run the password encryption command
          kubectl exec -i ${{ inputs.pod_name }} -c ${{ inputs.container_name }} -- /bin/bash -c "./password_manager -g -k /opt/actimize/ais_server/Instances/actimize_server_1/ais.keystore -a '${{ inputs.root_password }}' || echo 'Error running password_manager'"


    #   - name: Encrypt the root password
    #     run: |
    #       # Define the command to run in the container
    #       ENCRYPT_COMMAND="echo '${{ inputs.root_password }}' | base64"

    #       # Check if container name is provided
    #       if [[ -n "${{ inputs.container_name }}" ]]; then
    #         kubectl exec -it ${{ inputs.pod_name }} -c ${{ inputs.container_name }} -- /bin/bash -c "$ENCRYPT_COMMAND"
    #       else
    #         kubectl exec -it ${{ inputs.pod_name }} -- /bin/bash -c "$ENCRYPT_COMMAND"
    #       fi
    #     shell: bash
