name: 05-UpdatePassword secret

on: 
  workflow_dispatch: 
    inputs:
      secret_name:
        description: "Enter the Google Secret Manager secret name"
        default: "secret-auto-123"
        required: true
      pod_name:
        description: "Enter the pod name where the container is running"
        required: true
        type: string
      container_name:
        description: "Enter the container name (optional)"
        required: false
        type: string
      gke_cluster_name:
        description: 'Select the GKE cluster name'
        default: 'sap-dev-gke-cluster'
        required: true
        type: choice
        options:
          - 'tmproject-dev-private-cluster'
          - 'sap-dev-gke-cluster'
      gcp_project:
        description: 'Select the project'
        default: 'turnkey-guild-441104-f3'
        required: true
        type: choice
        options:
          - 'turnkey-guild-441104-f3'
      gcp_region_zone:
        description: 'Select the region or zone'
        default: 'zone'
        required: true
        type: choice
        options:
          - 'zone'
          - 'region'
      gcp_location:
        description: 'Select the location'
        default: 'us-east1-b'
        required: true
        type: choice
        options:
          - 'us-east1-b'
          - 'asia-southeast1'

jobs:
  k8s-deployment-2:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4
      
      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ inputs.action.gcp_project }}
          install_components: 'beta'
      
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Install gke-gcloud-auth-plugin
        run: |
            gcloud components install gke-gcloud-auth-plugin
      
      - name: Authenticate with GKE
        run: |
          gcloud container clusters get-credentials ${{inputs.gke_cluster_name}} \
          --${{inputs.gcp_region_zone}} ${{inputs.gcp_location}}

     
      - name: Retrieve Secret from Google Secret Manager
        id: retrieve-secret
        run: |
            # Fetch the secret value from Google Secret Manager
            SECRET_VALUE=$(gcloud secrets versions access latest \
                --secret=${{ inputs.secret_name }} \
                --project=${{ inputs.gcp_project }})

            if [[ -z "$SECRET_VALUE" ]]; then
                echo "Error: Secret value could not be retrieved."
                exit 1
            fi

            echo "SECRET_VALUE=$SECRET_VALUE" >> $GITHUB_ENV
      shell: bash
  
        - name: Verify Secret Retrieval
          run: |
            echo "Retrieved secret successfully."
            echo "The secret starts with: ${SECRET_VALUE:0:5}****" # Mask for security
  
        - name: Encrypt Password Inside Container
          run: |
            # Check if password_manager exists
            kubectl exec -i ${{ inputs.pod_name }} -c ${{ inputs.container_name }} -- which password_manager || echo "password_manager not found"
  
            # Run encryption command with retrieved secret
            kubectl exec -i ${{ inputs.pod_name }} -c ${{ inputs.container_name }} -- /bin/bash -c "./password_manager -g -k /opt/actimize/ais_server/Instances/actimize_server_1/ais.keystore -a '${SECRET_VALUE}' || echo 'Error running password_manager'"
          shell: bash