name: 08-helm-artifact registry

on: 
  workflow_dispatch: 
    inputs:
      action:
        description: "Action to perform with the Helm chart (apply or delete)"
        default: none
        type: choice
        options:
          - apply
          - delete
        required: true
      gke_cluster_name:
        description: 'Select the GKE cluster name'
        default: 'sap-dev-gke-cluster'
        required: true
        type: choice
        options:
          - 'tmproject-dev-private-cluster'
          - 'sap-dev-gke-cluster'
          - 'gke-public-cluster'
      gcp_project:
        description: 'Select the project'
        default: 'turnkey-guild-441104-f3'
        required: true
        type: choice
        options:
          - 'turnkey-guild-441104-f3'
      gcp_region_zone:
        description: 'Select region or zone'
        default: 'zone'
        required: true
        type: choice
        options:
          - 'zone'
          - 'region'
      gcp_location:
        description: 'Select the location'
        default: 'us-east1-b'
        required: true
        type: choice
        options:
          - 'us-east1-b'
          - 'asia-southeast1'
          - 'us-central1'
      helm_chart_version:
        description: 'Specify the Helm chart version'
        default: '1.0.5'
        required: true

jobs:
  k8s-deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4
      
      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ inputs.gcp_project }}
          install_components: 'beta'
      
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Install gke-gcloud-auth-plugin
        run: |
          gcloud components install gke-gcloud-auth-plugin -q
      
      - name: Authenticate with GKE
        run: |
          gcloud container clusters get-credentials ${{ inputs.gke_cluster_name }} \
          --${{ inputs.gcp_region_zone }} ${{ inputs.gcp_location }}

      - name: Install Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.11.1  # Adjust Helm version as needed

      - name: Authenticate Helm with Artifact Registry
        run: |
          gcloud auth print-access-token | helm registry login -u oauth2accesstoken --password-stdin us-central1-docker.pkg.dev

      - name: Pull Helm Chart from Artifact Registry
        run: |
          export REGISTRY_URL="us-central1-docker.pkg.dev/${{ inputs.gcp_project }}/helm"
          helm pull oci://$REGISTRY_URL/myapp --version ${{ inputs.helm_chart_version }}
          ls -al myapp-${{ inputs.helm_chart_version }}.tgz

      - name: Apply Helm chart
        if: ${{ inputs.action == 'apply' }}
        run: |
          helm upgrade --install myapp ./myapp-${{ inputs.helm_chart_version }}.tgz --namespace default --create-namespace
      
      - name: Uninstall Helm release
        if: ${{ inputs.action == 'delete' }}
        run: |
          helm uninstall myapp --namespace default
