name: 11-helm-deployment

on:
  workflow_dispatch:
    inputs:
      action:
        description: "Action to perform with the Helm charts (apply or delete)"
        default: none
        type: choice
        options:
          - apply
          - delete
        required: true
      gke_cluster_name:
        description: 'Select the GKE cluster name'
        default: 'sap-dev-gke-cluster'
        required: true
        type: choice
        options:
          - 'tmproject-dev-private-cluster'
          - 'sap-dev-gke-cluster'
          - 'gke-public-cluster'
      gcp_project:
        description: 'Select the project'
        default: 'turnkey-guild-441104-f3'
        required: true
        type: choice
        options:
          - 'turnkey-guild-441104-f3'
      gcp_region_zone:
        description: 'Select region or zone'
        default: 'zone'
        required: true
        type: choice
        options:
          - 'zone'
          - 'region'
      gcp_location:
        description: 'Select the location'
        default: 'us-east1-b'
        required: true
        type: choice
        options:
          - 'us-east1-b'
          - 'asia-southeast1'
          - 'us-central1'
      frontend_helm_chart_version:
        description: "Set the Helm chart version for frontend"
        default: "1.0.0"
        required: true
      backend_helm_chart_version:
        description: "Set the Helm chart version for backend"
        default: "1.0.0"
        required: true

jobs:
  helm-deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ inputs.gcp_project }}
          install_components: 'beta'

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Install gke-gcloud-auth-plugin
        run: |
          gcloud components install gke-gcloud-auth-plugin -q

      - name: Authenticate with GKE
        run: |
          gcloud container clusters get-credentials ${{ inputs.gke_cluster_name }} \
            --${{ inputs.gcp_region_zone }} ${{ inputs.gcp_location }}

      - name: Install Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.11.1  # Adjust Helm version as needed

      # Apply or upgrade Frontend Helm chart
      - name: Apply Frontend Helm Chart
        if: ${{ inputs.action == 'apply' }}
        run: |
          helm upgrade --install frontend ./04-Internship-deployment/charts/frontend \
            --namespace default \
            --set image.tag=${{ inputs.frontend_helm_chart_version }} \
            --create-namespace

      # Apply or upgrade Backend Helm chart
      - name: Apply Backend Helm Chart
        if: ${{ inputs.action == 'apply' }}
        run: |
          helm upgrade --install backend ./04-Internship-deployment/charts/backend \
            --namespace default \
            --set image.tag=${{ inputs.backend_helm_chart_version }} \
            --create-namespace

      # Uninstall Frontend Helm release
      - name: Uninstall Frontend Helm Chart
        if: ${{ inputs.action == 'delete' }}
        run: |
          helm uninstall frontend --namespace default

      # Uninstall Backend Helm release
      - name: Uninstall Backend Helm Chart
        if: ${{ inputs.action == 'delete' }}
        run: |
          helm uninstall backend --namespace default
